---
# handlers file for deploy_apache_web
- name: Restart apache RedHat
  when: ansible_os_family == "RedHat"
  service: name=httpd state=restarted

- name: Restart apache Debian
  when: ansible_os_family == "Debian"
  service: name=apache2 state=restarted