- block: #====== Block for RedHat
    - name: Install apache for RedHat
      yum: name=httpd state=latest

    - name: Run apache for RedHat
      service: name=httpd state=started enabled=yes
  when: ansible_os_family == "RedHat"