---
# tasks file for deploy_apache_web
- name: Check and print OS version
  debug:
    var: ansible_os_family

- name: Install apache Debian
  include_tasks: installApacheDebian.yml

- name: Install apache RedHat
  include_tasks: installApacheRedHat.yml

- name: Copy files
  copy: src={{ source_file }} dest={{ destination_path }} mode=0555
  notify:
    - Restart apache RedHat
    - Restart apache Debian
