---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bangok
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bangok-pod
  template:
    metadata:
      labels:
        app: bangok-pod
    spec:
      containers:
        - name: bangok
          image: ihorstoner/bangok:latest
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling-bangok
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: bangok
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 50


