---
- name: Install LAMP stack
  hosts: tag_Name_LAMP
  become: yes

#  tasks:
#    - name: Check and print OS version
#      debug:
#        var: ansible_os_family

  roles:
    - { role: apache, when: ansible_system == 'Linux' }
    - { role: php, when: ansible_system == 'Linux' }
    - { role: mariadb, when: ansible_system == 'Linux' }
